server:
  port: 8083

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/RatingMS
    username: root
    password: Stick@123
    driver-class-name: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
              
  application:
    name: RATING-SERVICE



        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-88604293.okta.com/oauth2/default
    audience: api://default
    

    